### ISSUE TITLE
Add Accept headers to request, in order to avoid blocking because of mod_security default

### ISSUE THREAD

**Issue by boldip** [LAW-Unimi/BUbiNG#1]
As suggested (via e-mail): 

You bot is being blocked by default with mod_security users with the core rule set due to a missing Accept: headers...

Sample log entry...

[Wed Aug 09 17:31:43.092235 2017] [:error] [pid 24450] [client 64.62.252.164] ModSecurity: Warning. Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "www.atitd.com"] [uri "/"] [unique_id "WYtG-07PGRyBBSPejSylKgAAAAg"]

**Comment by vigna** [comment]
We added the "Accept" header in the last commits.
