### ISSUE TITLE
Any simple tutorial on how to start Bubing

### ISSUE THREAD

**Issue by GaneshVarahade** [LAW-Unimi/BUbiNG#21]
Hi Team,

Apologies for asking help on Github Issues, can anyone please guide me to a simple Tutorial on how to setup Bubbing for crawling?

Thanks in Advance

**Comment by VAle512** [comment]
Hi,
I'm not part of the team, but I suggest you to follow the [overview](https://github.com/LAW-Unimi/BUbiNG/blob/master/src/overview.html) (in the src folder). It is pretty clear and I used it to start the crawler a couple of years ago.
