### ISSUE TITLE
URLMatchesRegex seems not to be working

### ISSUE THREAD

**Issue by beviah** [LAW-Unimi/BUbiNG#28]
Due to provider warnings for network scans, I want to block direct requests to IP addresses (some end up being unrouted and trigger warnings), so only to allow domain names.. 

I add to the config file the following filter which works in JAVA:

```
scheduleFilter=not URLMatchesRegex(.*//[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?.*)
followFilter=not URLMatchesRegex(.*//[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?.*)
```

yet it keeps crawling IPs, and I keep getting abuse warnings from the host provider. 

One possible reason why they get through is that this type of URL may be followed (its redirect):

http://example.com/?ip=123.123.123.213

But blocking those would not always solve the problem, as redirect may have a hash instead of IP, so could not be detected it in advance.. 

Any idea what may be wrong?

**Comment by vigna** [comment]
Shouldn't the regexes start with .* ?

**Comment by boldip** [comment]
The Regex is matched against the whole URL (your expression matches only a substring of the URL --- erm, not even that to be honest because of the starting .//)

**Comment by beviah** [comment]
ah, github removed the star.. 
it has dot star both at the end and begining. github interpreted it as italic :(
edited it now above, it is in codeblock

**Comment by vigna** [comment]
First I would check that it is happening. Run a fake crawl with a single seed given by an IP address and see what happens...

**Comment by beviah** [comment]
I did run a fake crawl and it wasn't happening.. that is why I am suspecting at redirects.. I could run a crawl with fake redirects as well..

**Comment by beviah** [comment]
I mean, it wasn't happening with seeds, but it may be fetching those through page parsing as well..

**Comment by boldip** [comment]
I added a new test ([https://github.com/LAW-Unimi/BUbiNG/commit/50769f87a1ce13bc2f7335866eb9b8b79cd668c2](https://github.com/LAW-Unimi/BUbiNG/commit/50769f87a1ce13bc2f7335866eb9b8b79cd668c2)) with a filter that works as you want. It is subtly different from the one shown above (it is not clear to me whether you just mis-copied it or what).

**Comment by beviah** [comment]
Yes, that one will remove redirects as well.. but my question is, what if URL has a hash instead of IP, and is a redirect to non-routed IP, will it be crawled if this filter is applied?

**Comment by beviah** [comment]
In other words, is the filter also applied after the redirect URL is known?

**Comment by vigna** [comment]
Yes, redirects are treated like any other URL. See the `enqueue()` method in ParsingThread.

I can only suggest a run with logging set to DEBUG, so you will be able to see which URLs are discarded by the scheduleFilter.

**Comment by beviah** [comment]
Ok.. will do that.. and report here new results.. though still think something may be off, as my regex works properly for IP based urls..

**Comment by vigna** [comment]
Yes, but, for example, you can specify an IP URL using a 32-bit number instead of the dotted notation.

**Comment by beviah** [comment]
hmm, that may be it! maybe someone is linking to integer addresses :) 
will block integers as well.. in domain place.. not URL path.

**Comment by beviah** [comment]
Still fetching IPs. 


nohup.out:

`
[Cache-Control: private, Content-Type: text/html, Location: http://94.136.40.51/kbcc.space/index.html, Server: Microsoft-IIS/8.5, Date: Sat, 06 Nov 2021 13:16:51 GMT, Content-Length: 0]
[Server: nginx, Date: Sat, 06 Nov 2021 13:18:22 GMT, Content-Type: text/html; charset=iso-8859-1, Content-Length: 225, Connection: keep-alive, Location: http://127.0.0.1/, X-XSS-Protection: 1; mode=block, X-Content-Type-Options: nosniff, X-Nginx-Cache-Status: BYPASS, X-Server-Powered-By: Engintron]
`

current.properties:

`
fetchFilter=true
scheduleFilter=not URLMatchesRegex(.*//[0-9.:]+/.*)
followFilter=not URLMatchesRegex(.*//[0-9.:]+/.*)
`

Just noticed that fetchFilter=true.. 

Does that one needs regex as well? but it's confusing, if i don't follow IPs, why would it fetch it? 


Just tested now, even with fetchFilter with same regex it fetches IPs.

**Comment by vigna** [comment]
Yes, but did you enable DEBUG? Did you see why it's happening?

**Comment by beviah** [comment]
I used -Xdebug flag. above is all the info I get.

**Comment by vigna** [comment]
Not what I said. You have to set the logging level to DEBUG. You have to configure logback.

**Comment by beviah** [comment]
Ah, totally forgot about that one. 

Here are few example lines:


2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php[\r][\n]"
2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.headers - http-outgoing-53864 << x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php
2021-11-06 17:08:43,577 419153 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd" />[\n]"
2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - Analyzing http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd for enqueuing
2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - I'm not scheduling URL http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd: not accepted by scheduleFilter

they contradict what i find in output


[date: Sat, 06 Nov 2021 16:08:39 GMT, server: Apache/2.4.51 (Unix), x-powered-by: PHP/5.3.28, x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php, transfer-encoding: chunked, content-type: text/html; charset=UTF-8]

**Comment by vigna** [comment]
Did you check in your seed? The log says clearly that it has not been scheduled...

**Comment by beviah** [comment]
I have only domains in seeds, no IPs, or anything matching above regex..

**Comment by vigna** [comment]
Well, there are only 2 places where a URL can be enqueued: initially from the seed, or from the ParsingThread. The second case is not possible as you seem from the log (check the code). The only thing I can think of is that's in the seed... can you check in which pages the URL appears? You have to look at the last page analyzed by the thread printing the stuff above about not scheduling the URL.

**Comment by vigna** [comment]
You can also put the log somewhere, I can have a look. Also the seed file for the crawl.

**Comment by beviah** [comment]
Reverse IP for above points to web16.extendcp.co.uk., which is marked as deceptive site by Firefox. 

log file has 40+GB.. so tricky to load it anywhere :) i am attaching below relevant snippets
seeds have 30 million domains, wanted to test it on real data..

**Comment by beviah** [comment]
here is partial log, with 100 line contexts
[partial.log](https://github.com/LAW-Unimi/BUbiNG/files/7491387/partial.log)
 around above IP.

**Comment by vigna** [comment]
> Ah, totally forgot about that one.
> 
> Here are few example lines:
> 
> 2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "x-pingback: [http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php[\r][\n]](http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php%5B%5Cr%5D%5B%5Cn%5D)" 2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.headers - http-outgoing-53864 << x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php 2021-11-06 17:08:43,577 419153 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "[\n]" 2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - Analyzing http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd for enqueuing 2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - I'm not scheduling URL http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd: not accepted by scheduleFilter
> 
> they contradict what i find in output
> 
> [date: Sat, 06 Nov 2021 16:08:39 GMT, server: Apache/2.4.51 (Unix), x-powered-by: PHP/5.3.28, x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php, transfer-encoding: chunked, content-type: text/html; charset=UTF-8]

The two links are not the same. Watch more carefully, please.

**Comment by beviah** [comment]
hmm, but the one without ?rsd is nowhere in debug log paired with 
Analyzing ... 

yet it is visited.. strange.. 

```

root@bubing /tmp # more bubing.* | grep '176.32.230.16' | grep xmlrpc
2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php[\r][\n]"
2021-11-06 17:08:43,554 419130 DEBUG [FetchingThread-45] o.a.h.headers - http-outgoing-53864 << x-pingback: http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php
2021-11-06 17:08:43,577 419153 DEBUG [FetchingThread-45] o.a.h.wire - http-outgoing-53864 << "<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd" />[\n]"
2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - Analyzing http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd for enqueuing
2021-11-06 17:08:43,681 419257 DEBUG [ParsingThread-63] i.u.d.l.b.f.ParsingThread - I'm not scheduling URL http://176.32.230.16/experiencethemovement.co.uk/xmlrpc.php?rsd: not accepted by scheduleFilter

```

**Comment by vigna** [comment]
OK, there's a super weird possibility: that that URL is met during redirects of a robots.txt download, because those redirects are handled internally by the Apache HTTP client.

**Comment by beviah** [comment]
ah, makes sense... seems the mystery has an explanation :)

thanks!

**Comment by beviah** [comment]
@vigna  just to confirm that you were right, all the remaining IPs (after firewall and regex blocking) that occur in logs come right after robots.txt file fetching, so those indeed are internal redirects.

**Comment by vigna** [comment]
OK. What you can do is (in the code) set the number of redirects to 0. But then in principle you might miss some robots.txt.

https://github.com/LAW-Unimi/BUbiNG/blob/50769f87a1ce13bc2f7335866eb9b8b79cd668c2/src/it/unimi/di/law/bubing/frontier/Frontier.java#L468

**Comment by beviah** [comment]
thanks. will do some analysis to see what would be the miss rate..
